OSOE-650: Add UI test project in Lombiq.JsonEditor
Lombiq/Orchard-JSON-Editor pull request #45
Opened 2023-08-05 16:02 UTC by DemeSzabolcs

OSOE-650

2023-08-07 21:33 UTC, Piedone requested changes

2023-08-07 21:33 UTC, Piedone commented on .editorconfig
Don't commit this, nor _Lombiq.JsonEditor/.editorconfig_.

2023-08-07 21:33 UTC, Piedone commented on Lombiq.JsonEditor.Test.UI/Extensions/TestCaseUITestContextExtensions.cs
I get this in the log when running the test locally and the test fails:

```
[2023-08-07T21:20:44Z] [Severe] https://localhost:9324/Admin/Contents/ContentItems/4xapn6ykttkk6wbbwgg1aaxqda/Edit - Refused to apply style from 'https://localhost:9324/Lombiq.JsonEditor/css/json-editor.css' because its MIME type ('') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

2023-08-07 21:33 UTC, Piedone commented on Lombiq.JsonEditor.Test.UI/Extensions/TestCaseUITestContextExtensions.cs
> +        context.GetAll(By.XPath($"//button[@class='jsoneditor-button jsoneditor-contextmenu-button']"))[1].Click();
Can't you target the button more directly instead of relying on the matched elements' order?

2023-08-07 21:33 UTC, Piedone commented on Lombiq.JsonEditor.Test.UI/Extensions/TestCaseUITestContextExtensions.cs
> +        }
Use `CheckExistence()` instead.

2023-08-07 21:33 UTC, Piedone commented on Lombiq.JsonEditor.Test.UI/License.md
> +Copyright © 2023, [Lombiq Technologies Ltd.](https://lombiq.com)
Use the existing license.

2023-08-07 21:33 UTC, Piedone commented on Lombiq.JsonEditor.Test.UI/Lombiq.JsonEditor.Tests.UI.csproj
> +    <Copyright>Copyright © 2023, Lombiq Technologies Ltd.</Copyright>
Use the original copyright year.

2023-08-07 21:33 UTC, Piedone commented on Lombiq.JsonEditor/Lombiq.JsonEditor.sln
> +﻿
Why is this needed? It shouldn't be, only the root sln.

2023-08-08 12:29 UTC, DemeSzabolcs commented on Lombiq.JsonEditor.Test.UI/Extensions/TestCaseUITestContextExtensions.cs
> +        context.GetAll(By.XPath($"//button[@class='jsoneditor-button jsoneditor-contextmenu-button']"))[1].Click();
I will try to find a better way.

2023-08-08 13:47 UTC, DemeSzabolcs commented on Lombiq.JsonEditor.Test.UI/Extensions/TestCaseUITestContextExtensions.cs
It's bad for me too now, but it was working so far :)

2023-08-08 14:02 UTC, DemeSzabolcs commented on Lombiq.JsonEditor.Test.UI/Extensions/TestCaseUITestContextExtensions.cs
Running the test for the second time, or building the app first and navigating to the JSON editor fixes it. If you clean the repo, then run the test first without doing anything else locally, the css will not load. But I think we have seen this behavior before.

2023-08-08 15:28 UTC, Piedone commented on Lombiq.JsonEditor.Test.UI/Extensions/TestCaseUITestContextExtensions.cs
We experienced this in LMBQ I think (or NEST).

2023-08-08 16:34 UTC, Piedone requested changes

2023-08-08 16:34 UTC, Piedone commented on Lombiq.JsonEditor.sln
Why did you delete this? This is needed for NuGet publishign, but not the other one in the module's folder.

2023-08-08 16:34 UTC, Piedone commented on Lombiq.JsonEditor.Test.UI/Extensions/TestCaseUITestContextExtensions.cs
This is still the case (even running the app normally first and visiting the sample content item, or running the test twice, which shouldn't be necessary anyway).

2023-08-08 16:51 UTC, DemeSzabolcs commented on Lombiq.JsonEditor.Test.UI/Extensions/TestCaseUITestContextExtensions.cs
Then I guess it's a local problem, and I don't think it's possible to fix it from code. I had a similar problem with `js` and I solved it like this: https://stackoverflow.com/a/52800549/16192320

2023-08-08 16:52 UTC, DemeSzabolcs commented on Lombiq.JsonEditor.sln
Oops wrong sln

2023-08-08 17:08 UTC, Piedone commented on Lombiq.JsonEditor.Test.UI/Extensions/TestCaseUITestContextExtensions.cs
This is specific to just this test, all the other tests pass for me, though many of them use custom CSS. The registry config is correct for me.

2023-08-08 18:38 UTC, DemeSzabolcs commented on Lombiq.JsonEditor.Test.UI/Extensions/TestCaseUITestContextExtensions.cs
Please pull from the branch and test it. I think I fixed it. If it's working I will put the issue to Done.

2023-08-08 19:02 UTC, Piedone commented on Lombiq.JsonEditor.Test.UI/Extensions/TestCaseUITestContextExtensions.cs
Work now!

2023-08-08 19:03 UTC, Piedone approved these changes

2023-08-08 19:30 UTC, merged